### ISSUE TITLE
Migrate does not work due to the transaction not mined within 750 seconds

### ISSUE THREAD

**Issue by gliatti** [neha01/nft-demo#2]
Hello Neha,

The following command does not work on the mainnet :
```
npx truffle migrate --network matic
```
Here is my `.env` file :
```
PINATA_API_KEY="*"
PINATA_API_SECRET="*"
PINATA_ENDPOINT="https://api.pinata.cloud/pinning/pinFileToIPFS"
MNEMONIC="*"
CLIENT_URL="https://polygon-rpc.com/"
CONTRACT_ADDRESS="YOUR_DEPLOYED_CONTRACT_ADDRESS"
```

The transaction are visible on polygonscan but I get an error when I reach 750 seconds with the following error :
```
Error:  *** Deployment Failed ***
"Migrations" -- Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!.

    at /home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
    at Migration._load (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/home/robin/Documents/backup/nft-demo/node_modules/truffle/build/webpack:/packages/core/lib/command.js:172:1)
Truffle v5.4.8 (core: 5.4.8)
Node v12.18.2
```

Here is a transaction example https://polygonscan.com/tx/0x9fdb1d9418ed6b430f3e54255f05b92801e80cf28dc2612dcaa44c53b19ddbe5

Don't we need to set gasPrice or gas in the matic provider ?

Thanks,

**Comment by neha01** [comment]
Hey Robin,
Yes we should set a gas & gasPrice for matic network. 
This error is likely happening because of not setting the gas ,so a default value is picked which might be lower gas as compared to other transactions in pool.
 I have now set gas and gasPrice for matic network in truffle config here:
 https://github.com/neha01/nft-demo/blob/deploy-polygon/truffle-config.js#L93
