### ISSUE TITLE
i ma getting an error after i run 'node scripts/runScript.js'

### ISSUE THREAD

**Issue by PlasticRico** [neha01/nft-demo#3]
i ma getting an error after i run 'node scripts/runScript.js'
Error occured while storing data to file Error: Configuration property "ipfsFile.location" is not defined
    at Config.get (C:\Windows\System32\nft-demo\node_modules\config\lib\config.js:182:11)
    at storeDataToFile (C:\Windows\System32\nft-demo\scripts\ipfsHelper.js:10:50)
    at pinFileToIPFS (C:\Windows\System32\nft-demo\scripts\pinFileToIPFS.js:29:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Successfully added IPFS response to json file
it dose not  create in data folder ipfsHash.json file

**Comment by Mohd-Taqiuddin** [comment]
Try running this command "export NODE_ENV=dev"
