### ISSUE TITLE
Pinning to IPFS failing

### ISSUE THREAD

**Issue by SurajGutti** [neha01/nft-demo#5]
Hi Neha,

I get a similar error to the one mentioned earlier - 
Error occured while storing data to file Error: Configuration property "ipfsFile.location" is not defined
    at Config.get (D:\GitHub\yoriverse\node_modules\config\lib\config.js:182:11)
    at storeDataToFile (D:\GitHub\yoriverse\scripts\ipfsHelper.js:10:50)
    at pinFileToIPFS (D:\GitHub\yoriverse\scripts\pinFileToIPFS.js:29:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Successfully added IPFS response to json file

Prior to this error I also get the output 
data: {
    IpfsHash: 'QmbAVkKcEiLSjXUYpYuTKipJYZmoVgeV85PahG6Fp1D5Sc',
    PinSize: 224676,
    Timestamp: '2022-05-22T12:00:50.187Z',
    isDuplicate: true
  }

But no data folder is being created.

I tried setting the NODE_ENV to dev. Anything else I am missing?

**Comment by lennon7c7** [comment]
Hi SurajGutti
You should create default.json just like dev.json, or just rename dev.json to default.json
